package com.sml.pojo;
// Generated 2017-12-22 20:09:00 by Hibernate Tools 5.2.6.Final

/**
 * Option generated by hbm2java
 */
public class Option implements java.io.Serializable {

	private Integer OId;
	private Long version;
	private Vote vote;
	private String content;
	private Integer count;
	private byte[] img;

	public Option() {
	}

	public Option(Vote vote, String content, Integer count, byte[] img) {
		this.vote = vote;
		this.content = content;
		this.count = count;
		this.img = img;
	}

	public Integer getOId() {
		return this.OId;
	}

	public void setOId(Integer OId) {
		this.OId = OId;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Vote getVote() {
		return this.vote;
	}

	public void setVote(Vote vote) {
		this.vote = vote;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public byte[] getImg() {
		return this.img;
	}

	public void setImg(byte[] img) {
		this.img = img;
	}

}
