package com.sml.pojo;
// Generated 2017-12-22 20:09:00 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Vote generated by hbm2java
 */
public class Vote implements java.io.Serializable {

	private Integer VId;
	private Long version;
	private String title;
	private Set options = new HashSet(0);

	public Vote() {
	}

	public Vote(String title, Set options) {
		this.title = title;
		this.options = options;
	}

	public Integer getVId() {
		return this.VId;
	}

	public void setVId(Integer VId) {
		this.VId = VId;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getOptions() {
		return this.options;
	}

	public void setOptions(Set options) {
		this.options = options;
	}

}
