package com.sml.pojo;
// Generated 2017-12-21 19:05:50 by Hibernate Tools 5.2.6.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int uid;
	private Character username;
	private Character password;

	public Users() {
	}

	public Users(int uid) {
		this.uid = uid;
	}

	public Users(int uid, Character username, Character password) {
		this.uid = uid;
		this.username = username;
		this.password = password;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public Character getUsername() {
		return this.username;
	}

	public void setUsername(Character username) {
		this.username = username;
	}

	public Character getPassword() {
		return this.password;
	}

	public void setPassword(Character password) {
		this.password = password;
	}

}
