package com.sml.pojo;
// Generated 2017-12-21 21:43:31 by Hibernate Tools 5.2.6.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int uid;
	private String username;
	private String password;

	public Users() {
	}

	public Users(int uid) {
		this.uid = uid;
	}

	public Users(int uid, String username, String password) {
		this.uid = uid;
		this.username = username;
		this.password = password;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
